In [ ]:
import numpy as np

In [ ]:
#Set A
def replace_array_A(arr):
  row, col = arr.shape
  row_sum = np.zeros(row, dtype=int)
  col_sum = np.zeros(col, dtype=int)
  for i in range(row):
    for j in range(col):
      row_sum[i] += arr[i][j]
      col_sum[j] += arr[i][j]
  for i in range(row):
    for j in range(col):
      arr[i][j] = (row_sum[i] - arr[i][j]) * (col_sum[j] - arr[i][j])
  return arr

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [9, 8, 7],
                [2, 8, 1]], dtype = int)
output = replace_array_A(arr)
print(output)


[[ 75  84  42]
 [132 180  99]
 [105 240 170]
 [126  45 160]]


In [ ]:
def replace_array_B(arr):
  row, col = arr.shape
  row_prod = np.ones(row, dtype=int)
  col_prod = np.ones(col, dtype=int)
  for i in range(row):
    for j in range(col):
      row_prod[i] *= arr[i][j]
      col_prod[j] *= arr[i][j]
  for i in range(row):
    for j in range(col):
      arr[i][j] = (row_prod[i] / arr[i][j]) + (col_prod[j] / arr[i][j])
  return arr

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [9, 8, 7],
                [2, 8, 1]], dtype = int)
output = replace_array_B(arr)
print(output)

[[ 78 323  44]
 [ 48 152  41]
 [ 64 143  90]
 [ 44  82 142]]


In [ ]:
# Rubric
 # Finding array shape (row and col) = 2
 # Interate through each row and col = 3
 # finding row sum or product = 3
 # finding col sum or product = 3
 # replacing i,j with magic number = 3
 # return the changed array = 1

 #N.B = Any alternative valid solution is also correct.