In [ ]:
# SET A
import numpy as np
def row_max(arr, row):
    max = arr[row][0]
    for i in range(1, len(arr[0])):
        if max < arr[row][i]:
            max = arr[row][i]
    return max

def col_max(arr, col):
    max = arr[0][col]
    for i in range(1, len(arr)):
        if max < arr[i][col]:
            max = arr[i][col]
    return max

def replace_array(arr):
    for r in range(len(arr)):
        r_max = row_max(arr, r)
        for c in range(len(arr[0])):
            c_max = col_max(arr, c)
            if r_max < c_max:
                arr[r][c] = r_max
            else:
                arr[r][c] = c_max
    return arr

arr = np.array([[7, 5, 6],
                [1, 8, 2],
                [9, 8, 7],
                [2, 8, 1],
                [4, 7, 3]], dtype = int)

print(replace_array(arr))



[[7 7 7]
 [8 8 7]
 [9 8 7]
 [8 8 7]
 [7 7 7]]


In [ ]:
# SET B
import numpy as np
def row_min(arr, row):
    min = arr[row][0]
    for i in range(1, len(arr[0])):
        if min > arr[row][i]:
            min = arr[row][i]
    return min

def col_min(arr, col):
    min = arr[0][col]
    for i in range(1, len(arr)):
        if min > arr[i][col]:
            min = arr[i][col]
    return min

def replace_array(arr):
    for r in range(len(arr)):
        r_min = row_min(arr, r)
        for c in range(len(arr[0])):
            c_min = col_min(arr, c)
            if r_min > c_min:
                arr[r][c] = r_min
            else:
                arr[r][c] = c_min
    return arr

arr = np.array([[5, 7, 6],
                [11, 4, 10],
                [3, 4, 5],
                [10, 4, 11],
                [8, 5, 9]], dtype = int)

print(replace_array(arr))



[[5 5 5]
 [4 4 5]
 [3 4 5]
 [4 4 5]
 [5 5 5]]


In [ ]:
# Rubric
 # Finding array shape (row and col) = 2
 # Interate through each row and col = 3
 # finding row max or min = 3
 # finding col max or min = 3
 # replacing i,j with min(row_max, col_max) (or vice versa) = 3
 # return the changed array = 1

 #N.B = Any alternative valid solution is also correct.